---
openapi: 3.1.0
info:
  title: Flowrapp API
  description: REST API for Flowrapp Backend
  version: 0.0.1
  contact:
    name: Flowrapp Team
    url: https://flowrapp.github.io
    email: flowraapp@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:8080/flowrapp
    description: Local server url

tags:
  - name: Users
    description: User management API
  - name: Authentication
    description: Authentication API
  - name: Admin
    description: Administrative API
  - name: Businesses
    description: Business management API
  - name: Worklogs
    description: Worklog management API
  - name: Reports
    description: Reporting API

paths:
  "/api/v1/users":
    $ref: 'v1/services/users/user-operations.yml#/users'
  "/api/v1/auth/login":
    $ref: 'v1/services/auth/auth-operations.yml#/auth/login'
  "/api/v1/auth/token-refresh":
    $ref: 'v1/services/auth/auth-operations.yml#/auth/token-refresh'
  "/api/v1/admin/register":
    $ref: 'v1/services/admin/admin-operations.yml#/admin/register'
  "/api/v1/businesses":
    $ref: 'v1/services/business/businesses-operations.yml#/businesses/get-businesses'
  "/api/v1/businesses/{businessId}/worklogs/clock-in":
    $ref: 'v1/services/worklogs/worklogs-operations.yml#/worklogs/clock-in'
  "/api/v1/businesses/{businessId}/worklogs/clock-out":
    $ref: 'v1/services/worklogs/worklogs-operations.yml#/worklogs/clock-out'
  "/api/v1/businesses/{businessId}/worklogs":
    $ref: 'v1/services/worklogs/worklogs-operations.yml#/worklogs/filtered-worklogs'
  "/api/v1/reports/weekly-hours":
    $ref: 'v1/services/reports/reports-operations.yml#/reports/weekly-hours'


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic authentication with username and password
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT-based authentication
