---
openapi: 3.1.0
info:
  title: Flowrapp API
  description: REST API for Flowrapp Backend
  version: 0.0.1
  contact:
    name: Flowrapp Team
    url: https://flowrapp.github.io
    email: info@flowrapp.github.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:8080/flowrapp
    description: Generated server url

tags:
  - name: Users
    description: User management API
  - name: Authentication
    description: Authentication API
  - name: Admin
    description: Administrative API
  - name: Businesses
    description: Business management API
  - name: Worklogs
    description: Worklog management API
  - name: Reports
    description: Reporting API

paths:
  "/api/v1/users":
    $ref: 'users/v1/services/user-operations.yml#/users'
  "/api/v1/auth":
    $ref: 'auth/v1/services/auth-operations.yml#/auth'
  "/api/v1/admin":
    $ref: 'admin/v1/services/admin-operations.yml#/admin'
  "/api/v1/businesses":
    $ref: 'businesses/v1/services/businesses-operations.yml#/businesses'
  "/api/v1/businesses/{businessId}/worklogs":
    $ref: 'worklogs/v1/services/worklogs-operations.yml#/worklogs'
  "/api/v1/reports":
    $ref: 'reports/v1/services/reports-operations.yml#/reports'


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic authentication with username and password
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT-based authentication