name: API Changes

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [develop]

jobs:
  changes:
    name: Detect and preview API changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: ${{secrets.BUMP_DOC_ID}}
          token: ${{secrets.BUMP_TOKEN}}
          file: api/open-api-rest.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy preview API changes
        uses: bump-sh/github-action@v1
        with:
          doc: ${{secrets.BUMP_DOC_ID}}
          token: ${{secrets.BUMP_TOKEN}}
          file: api/open-api-rest.yml
          command: preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: API Linting
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install @quobix/vacuum --include=dev

      - name: Lint API
        run: cd api && npm exec vacuum report -- --junit open-api-rest.yml lint-results

      - name: Publish Lint Results
        if: success() || failure()
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: API Lint Results
          report_paths: lint-results-*.xml