name: Deploy API documentation

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened
      - closed

env:
  STAINLESS_PROJECT_NAME: flowrapp

jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run preview builds
        uses: stainless-api/upload-openapi-spec-action/preview@v1
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          org: ${{ env.STAINLESS_ORG }}
          project: ${{ env.STAINLESS_PROJECT }}
          oas_path: ${{ env.OAS_PATH }}

  update-docs:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i -g @redocly/cli@latest

      - name: Bundle OpenAPI spec
        run: redocly bundle api/open-api-rest.yml -o api/bundle-openapi.yaml

      - name: Push spec file to Stainless
        id: stainless_upload
        uses: stainless-api/upload-openapi-spec-action/merge@v1
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          org: ${{ env.STAINLESS_ORG }}
          project: ${{ env.STAINLESS_PROJECT }}
          oas_path: ${{ env.OAS_PATH }}
          # Note: this file will be your spec extended with code samples
          output_dir: "./"

      - name: Debug - Print documented_spec_path
        run: echo "The documented_spec_path is ${{ steps.stainless_upload.outputs.documented_spec_path }}"

      - name: Deploy API docs to Bump.sh
        uses: bump-sh/github-action@v1
        with:
          doc: ${{secrets.BUMP_DOC_ID}}
          token: ${{secrets.BUMP_TOKEN}}
          # Using the documented_spec_path output from the stainless_upload step
          file: ${{ steps.stainless_upload.outputs.documented_spec_path }}
