name: OpenAPI Validation

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Swagger CLI
        run: npm install -g @apidevtools/swagger-cli

      - name: Validate OpenAPI files with Swagger CLI
        run: swagger-cli validate api/main-api/rest/open-api-rest.yml
