name: OpenAPI Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '../../api/**/*.yml'
      - '../../api/**/*.yaml'
  pull_request:
    paths:
      - '../../api/**/*.yml'
      - '../../api/**/*.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Swagger CLI
        run: npm install -g @apidevtools/swagger-cli

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Validate OpenAPI files with Swagger CLI
        run: |
          find apis -name "open-api-rest.yml" -o -name "open-api-rest.yaml" | while read file; do
            echo "Validating $file with Swagger CLI..."
            swagger-cli validate "$file" || exit 1
          done
